print('Hello There, What is your Name?')
Name = input("Write Your Name:")
print("Nice to Meet You!" +Name)
print("How Old are You?")
Age = input('Write Your Age:')
birth_year = 2021-int(Age)
#print(birth_year)
print("Your Birth Year Is-" +str(birth_year))
print("Good Luck")